import '../models/exercise.dart';
import 'categories.dart';

const kSeedExercises = [
  // ── Chest ──────────────────────────────────────────────────────────────────
  Exercise(
    id: 'ex_barbell_bench_press',
    name: 'Barbell Bench Press',
    primaryMuscle: MuscleGroup.chest,
    secondaryMuscles: [MuscleGroup.triceps, MuscleGroup.shoulders],
    equipment: Equipment.barbell,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_dumbbell_bench_press',
    name: 'Dumbbell Bench Press',
    primaryMuscle: MuscleGroup.chest,
    secondaryMuscles: [MuscleGroup.triceps, MuscleGroup.shoulders],
    equipment: Equipment.dumbbell,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_incline_barbell_press',
    name: 'Incline Barbell Press',
    primaryMuscle: MuscleGroup.chest,
    secondaryMuscles: [MuscleGroup.shoulders, MuscleGroup.triceps],
    equipment: Equipment.barbell,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_incline_dumbbell_press',
    name: 'Incline Dumbbell Press',
    primaryMuscle: MuscleGroup.chest,
    secondaryMuscles: [MuscleGroup.shoulders, MuscleGroup.triceps],
    equipment: Equipment.dumbbell,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_decline_barbell_press',
    name: 'Decline Barbell Press',
    primaryMuscle: MuscleGroup.chest,
    secondaryMuscles: [MuscleGroup.triceps],
    equipment: Equipment.barbell,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_cable_fly',
    name: 'Cable Fly',
    primaryMuscle: MuscleGroup.chest,
    secondaryMuscles: [MuscleGroup.shoulders],
    equipment: Equipment.cable,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_dumbbell_fly',
    name: 'Dumbbell Fly',
    primaryMuscle: MuscleGroup.chest,
    secondaryMuscles: [MuscleGroup.shoulders],
    equipment: Equipment.dumbbell,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_push_up',
    name: 'Push-Up',
    primaryMuscle: MuscleGroup.chest,
    secondaryMuscles: [MuscleGroup.triceps, MuscleGroup.shoulders],
    equipment: Equipment.bodyweight,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_chest_dip',
    name: 'Chest Dip',
    primaryMuscle: MuscleGroup.chest,
    secondaryMuscles: [MuscleGroup.triceps],
    equipment: Equipment.bodyweight,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_pec_deck',
    name: 'Pec Deck',
    primaryMuscle: MuscleGroup.chest,
    secondaryMuscles: [],
    equipment: Equipment.machine,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_machine_chest_press',
    name: 'Machine Chest Press',
    primaryMuscle: MuscleGroup.chest,
    secondaryMuscles: [MuscleGroup.triceps],
    equipment: Equipment.machine,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_low_cable_fly',
    name: 'Low Cable Fly',
    primaryMuscle: MuscleGroup.chest,
    secondaryMuscles: [],
    equipment: Equipment.cable,
    isCustom: false,
  ),

  // ── Back ───────────────────────────────────────────────────────────────────
  Exercise(
    id: 'ex_pull_up',
    name: 'Pull-Up',
    primaryMuscle: MuscleGroup.back,
    secondaryMuscles: [MuscleGroup.biceps],
    equipment: Equipment.bodyweight,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_chin_up',
    name: 'Chin-Up',
    primaryMuscle: MuscleGroup.back,
    secondaryMuscles: [MuscleGroup.biceps],
    equipment: Equipment.bodyweight,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_lat_pulldown',
    name: 'Lat Pulldown',
    primaryMuscle: MuscleGroup.back,
    secondaryMuscles: [MuscleGroup.biceps],
    equipment: Equipment.cable,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_seated_cable_row',
    name: 'Seated Cable Row',
    primaryMuscle: MuscleGroup.back,
    secondaryMuscles: [MuscleGroup.biceps],
    equipment: Equipment.cable,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_barbell_row',
    name: 'Barbell Row',
    primaryMuscle: MuscleGroup.back,
    secondaryMuscles: [MuscleGroup.biceps, MuscleGroup.core],
    equipment: Equipment.barbell,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_single_arm_dumbbell_row',
    name: 'Single Arm Dumbbell Row',
    primaryMuscle: MuscleGroup.back,
    secondaryMuscles: [MuscleGroup.biceps],
    equipment: Equipment.dumbbell,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_t_bar_row',
    name: 'T-Bar Row',
    primaryMuscle: MuscleGroup.back,
    secondaryMuscles: [MuscleGroup.biceps],
    equipment: Equipment.barbell,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_face_pull',
    name: 'Face Pull',
    primaryMuscle: MuscleGroup.back,
    secondaryMuscles: [MuscleGroup.shoulders],
    equipment: Equipment.cable,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_deadlift',
    name: 'Deadlift',
    primaryMuscle: MuscleGroup.back,
    secondaryMuscles: [MuscleGroup.hamstrings, MuscleGroup.glutes, MuscleGroup.core],
    equipment: Equipment.barbell,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_rack_pull',
    name: 'Rack Pull',
    primaryMuscle: MuscleGroup.back,
    secondaryMuscles: [MuscleGroup.hamstrings, MuscleGroup.glutes],
    equipment: Equipment.barbell,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_good_morning',
    name: 'Good Morning',
    primaryMuscle: MuscleGroup.back,
    secondaryMuscles: [MuscleGroup.hamstrings, MuscleGroup.glutes],
    equipment: Equipment.barbell,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_back_extension',
    name: 'Back Extension',
    primaryMuscle: MuscleGroup.back,
    secondaryMuscles: [MuscleGroup.glutes],
    equipment: Equipment.machine,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_wide_grip_pulldown',
    name: 'Wide Grip Pulldown',
    primaryMuscle: MuscleGroup.back,
    secondaryMuscles: [MuscleGroup.biceps],
    equipment: Equipment.cable,
    isCustom: false,
  ),

  // ── Shoulders ─────────────────────────────────────────────────────────────
  Exercise(
    id: 'ex_barbell_overhead_press',
    name: 'Barbell Overhead Press',
    primaryMuscle: MuscleGroup.shoulders,
    secondaryMuscles: [MuscleGroup.triceps, MuscleGroup.core],
    equipment: Equipment.barbell,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_dumbbell_overhead_press',
    name: 'Dumbbell Overhead Press',
    primaryMuscle: MuscleGroup.shoulders,
    secondaryMuscles: [MuscleGroup.triceps],
    equipment: Equipment.dumbbell,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_dumbbell_lateral_raise',
    name: 'Dumbbell Lateral Raise',
    primaryMuscle: MuscleGroup.shoulders,
    secondaryMuscles: [],
    equipment: Equipment.dumbbell,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_cable_lateral_raise',
    name: 'Cable Lateral Raise',
    primaryMuscle: MuscleGroup.shoulders,
    secondaryMuscles: [],
    equipment: Equipment.cable,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_dumbbell_front_raise',
    name: 'Dumbbell Front Raise',
    primaryMuscle: MuscleGroup.shoulders,
    secondaryMuscles: [],
    equipment: Equipment.dumbbell,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_arnold_press',
    name: 'Arnold Press',
    primaryMuscle: MuscleGroup.shoulders,
    secondaryMuscles: [MuscleGroup.triceps],
    equipment: Equipment.dumbbell,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_upright_row',
    name: 'Upright Row',
    primaryMuscle: MuscleGroup.shoulders,
    secondaryMuscles: [MuscleGroup.biceps],
    equipment: Equipment.barbell,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_machine_shoulder_press',
    name: 'Machine Shoulder Press',
    primaryMuscle: MuscleGroup.shoulders,
    secondaryMuscles: [MuscleGroup.triceps],
    equipment: Equipment.machine,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_rear_delt_fly',
    name: 'Rear Delt Fly',
    primaryMuscle: MuscleGroup.shoulders,
    secondaryMuscles: [MuscleGroup.back],
    equipment: Equipment.dumbbell,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_barbell_shrug',
    name: 'Barbell Shrug',
    primaryMuscle: MuscleGroup.shoulders,
    secondaryMuscles: [],
    equipment: Equipment.barbell,
    isCustom: false,
  ),

  // ── Biceps ────────────────────────────────────────────────────────────────
  Exercise(
    id: 'ex_barbell_curl',
    name: 'Barbell Curl',
    primaryMuscle: MuscleGroup.biceps,
    secondaryMuscles: [MuscleGroup.forearms],
    equipment: Equipment.barbell,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_dumbbell_curl',
    name: 'Dumbbell Curl',
    primaryMuscle: MuscleGroup.biceps,
    secondaryMuscles: [MuscleGroup.forearms],
    equipment: Equipment.dumbbell,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_hammer_curl',
    name: 'Hammer Curl',
    primaryMuscle: MuscleGroup.biceps,
    secondaryMuscles: [MuscleGroup.forearms],
    equipment: Equipment.dumbbell,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_incline_dumbbell_curl',
    name: 'Incline Dumbbell Curl',
    primaryMuscle: MuscleGroup.biceps,
    secondaryMuscles: [],
    equipment: Equipment.dumbbell,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_cable_curl',
    name: 'Cable Curl',
    primaryMuscle: MuscleGroup.biceps,
    secondaryMuscles: [MuscleGroup.forearms],
    equipment: Equipment.cable,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_ez_bar_curl',
    name: 'EZ-Bar Curl',
    primaryMuscle: MuscleGroup.biceps,
    secondaryMuscles: [MuscleGroup.forearms],
    equipment: Equipment.barbell,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_concentration_curl',
    name: 'Concentration Curl',
    primaryMuscle: MuscleGroup.biceps,
    secondaryMuscles: [],
    equipment: Equipment.dumbbell,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_preacher_curl',
    name: 'Preacher Curl',
    primaryMuscle: MuscleGroup.biceps,
    secondaryMuscles: [],
    equipment: Equipment.barbell,
    isCustom: false,
  ),

  // ── Triceps ───────────────────────────────────────────────────────────────
  Exercise(
    id: 'ex_cable_pushdown',
    name: 'Cable Pushdown',
    primaryMuscle: MuscleGroup.triceps,
    secondaryMuscles: [],
    equipment: Equipment.cable,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_overhead_tricep_extension_cable',
    name: 'Overhead Tricep Extension (Cable)',
    primaryMuscle: MuscleGroup.triceps,
    secondaryMuscles: [],
    equipment: Equipment.cable,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_skull_crushers',
    name: 'Skull Crushers',
    primaryMuscle: MuscleGroup.triceps,
    secondaryMuscles: [],
    equipment: Equipment.barbell,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_tricep_dip',
    name: 'Tricep Dip',
    primaryMuscle: MuscleGroup.triceps,
    secondaryMuscles: [MuscleGroup.chest],
    equipment: Equipment.bodyweight,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_dumbbell_kickback',
    name: 'Dumbbell Kickback',
    primaryMuscle: MuscleGroup.triceps,
    secondaryMuscles: [],
    equipment: Equipment.dumbbell,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_overhead_tricep_extension_dumbbell',
    name: 'Overhead Tricep Extension (Dumbbell)',
    primaryMuscle: MuscleGroup.triceps,
    secondaryMuscles: [],
    equipment: Equipment.dumbbell,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_machine_tricep_extension',
    name: 'Machine Tricep Extension',
    primaryMuscle: MuscleGroup.triceps,
    secondaryMuscles: [],
    equipment: Equipment.machine,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_diamond_push_up',
    name: 'Diamond Push-Up',
    primaryMuscle: MuscleGroup.triceps,
    secondaryMuscles: [MuscleGroup.chest],
    equipment: Equipment.bodyweight,
    isCustom: false,
  ),

  // ── Quadriceps ────────────────────────────────────────────────────────────
  Exercise(
    id: 'ex_barbell_squat',
    name: 'Barbell Squat',
    primaryMuscle: MuscleGroup.quads,
    secondaryMuscles: [MuscleGroup.glutes, MuscleGroup.hamstrings, MuscleGroup.core],
    equipment: Equipment.barbell,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_front_squat',
    name: 'Front Squat',
    primaryMuscle: MuscleGroup.quads,
    secondaryMuscles: [MuscleGroup.glutes, MuscleGroup.core],
    equipment: Equipment.barbell,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_leg_press',
    name: 'Leg Press',
    primaryMuscle: MuscleGroup.quads,
    secondaryMuscles: [MuscleGroup.glutes, MuscleGroup.hamstrings],
    equipment: Equipment.machine,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_leg_extension',
    name: 'Leg Extension',
    primaryMuscle: MuscleGroup.quads,
    secondaryMuscles: [],
    equipment: Equipment.machine,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_hack_squat',
    name: 'Hack Squat',
    primaryMuscle: MuscleGroup.quads,
    secondaryMuscles: [MuscleGroup.glutes],
    equipment: Equipment.machine,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_goblet_squat',
    name: 'Goblet Squat',
    primaryMuscle: MuscleGroup.quads,
    secondaryMuscles: [MuscleGroup.glutes, MuscleGroup.core],
    equipment: Equipment.kettlebell,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_bulgarian_split_squat',
    name: 'Bulgarian Split Squat',
    primaryMuscle: MuscleGroup.quads,
    secondaryMuscles: [MuscleGroup.glutes, MuscleGroup.hamstrings],
    equipment: Equipment.dumbbell,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_walking_lunge',
    name: 'Walking Lunge',
    primaryMuscle: MuscleGroup.quads,
    secondaryMuscles: [MuscleGroup.glutes, MuscleGroup.hamstrings],
    equipment: Equipment.dumbbell,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_smith_machine_squat',
    name: 'Smith Machine Squat',
    primaryMuscle: MuscleGroup.quads,
    secondaryMuscles: [MuscleGroup.glutes],
    equipment: Equipment.machine,
    isCustom: false,
  ),

  // ── Hamstrings ────────────────────────────────────────────────────────────
  Exercise(
    id: 'ex_romanian_deadlift',
    name: 'Romanian Deadlift',
    primaryMuscle: MuscleGroup.hamstrings,
    secondaryMuscles: [MuscleGroup.glutes, MuscleGroup.back],
    equipment: Equipment.barbell,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_leg_curl',
    name: 'Leg Curl',
    primaryMuscle: MuscleGroup.hamstrings,
    secondaryMuscles: [],
    equipment: Equipment.machine,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_stiff_leg_deadlift',
    name: 'Stiff Leg Deadlift',
    primaryMuscle: MuscleGroup.hamstrings,
    secondaryMuscles: [MuscleGroup.glutes, MuscleGroup.back],
    equipment: Equipment.dumbbell,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_sumo_deadlift',
    name: 'Sumo Deadlift',
    primaryMuscle: MuscleGroup.hamstrings,
    secondaryMuscles: [MuscleGroup.glutes, MuscleGroup.back],
    equipment: Equipment.barbell,
    isCustom: false,
  ),

  // ── Glutes ────────────────────────────────────────────────────────────────
  Exercise(
    id: 'ex_hip_thrust',
    name: 'Hip Thrust',
    primaryMuscle: MuscleGroup.glutes,
    secondaryMuscles: [MuscleGroup.hamstrings],
    equipment: Equipment.barbell,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_glute_bridge',
    name: 'Glute Bridge',
    primaryMuscle: MuscleGroup.glutes,
    secondaryMuscles: [MuscleGroup.hamstrings],
    equipment: Equipment.bodyweight,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_cable_kickback',
    name: 'Cable Glute Kickback',
    primaryMuscle: MuscleGroup.glutes,
    secondaryMuscles: [],
    equipment: Equipment.cable,
    isCustom: false,
  ),

  // ── Calves ────────────────────────────────────────────────────────────────
  Exercise(
    id: 'ex_standing_calf_raise',
    name: 'Standing Calf Raise',
    primaryMuscle: MuscleGroup.calves,
    secondaryMuscles: [],
    equipment: Equipment.machine,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_seated_calf_raise',
    name: 'Seated Calf Raise',
    primaryMuscle: MuscleGroup.calves,
    secondaryMuscles: [],
    equipment: Equipment.machine,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_donkey_calf_raise',
    name: 'Donkey Calf Raise',
    primaryMuscle: MuscleGroup.calves,
    secondaryMuscles: [],
    equipment: Equipment.machine,
    isCustom: false,
  ),

  // ── Core ──────────────────────────────────────────────────────────────────
  Exercise(
    id: 'ex_plank',
    name: 'Plank',
    primaryMuscle: MuscleGroup.core,
    secondaryMuscles: [],
    equipment: Equipment.bodyweight,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_crunch',
    name: 'Crunch',
    primaryMuscle: MuscleGroup.core,
    secondaryMuscles: [],
    equipment: Equipment.bodyweight,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_cable_crunch',
    name: 'Cable Crunch',
    primaryMuscle: MuscleGroup.core,
    secondaryMuscles: [],
    equipment: Equipment.cable,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_hanging_leg_raise',
    name: 'Hanging Leg Raise',
    primaryMuscle: MuscleGroup.core,
    secondaryMuscles: [],
    equipment: Equipment.bodyweight,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_ab_wheel_rollout',
    name: 'Ab Wheel Rollout',
    primaryMuscle: MuscleGroup.core,
    secondaryMuscles: [],
    equipment: Equipment.other,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_russian_twist',
    name: 'Russian Twist',
    primaryMuscle: MuscleGroup.core,
    secondaryMuscles: [],
    equipment: Equipment.bodyweight,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_decline_sit_up',
    name: 'Decline Sit-Up',
    primaryMuscle: MuscleGroup.core,
    secondaryMuscles: [],
    equipment: Equipment.bodyweight,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_bicycle_crunch',
    name: 'Bicycle Crunch',
    primaryMuscle: MuscleGroup.core,
    secondaryMuscles: [],
    equipment: Equipment.bodyweight,
    isCustom: false,
  ),

  // ── Forearms ──────────────────────────────────────────────────────────────
  Exercise(
    id: 'ex_wrist_curl',
    name: 'Wrist Curl',
    primaryMuscle: MuscleGroup.forearms,
    secondaryMuscles: [],
    equipment: Equipment.barbell,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_farmers_walk',
    name: "Farmer's Walk",
    primaryMuscle: MuscleGroup.forearms,
    secondaryMuscles: [MuscleGroup.core, MuscleGroup.shoulders],
    equipment: Equipment.dumbbell,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_dead_hang',
    name: 'Dead Hang',
    primaryMuscle: MuscleGroup.forearms,
    secondaryMuscles: [MuscleGroup.back],
    equipment: Equipment.bodyweight,
    isCustom: false,
  ),

  // ── Cardio ────────────────────────────────────────────────────────────────
  Exercise(
    id: 'ex_treadmill_run',
    name: 'Treadmill Run',
    primaryMuscle: MuscleGroup.cardio,
    secondaryMuscles: [],
    equipment: Equipment.machine,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_stationary_bike',
    name: 'Stationary Bike',
    primaryMuscle: MuscleGroup.cardio,
    secondaryMuscles: [],
    equipment: Equipment.machine,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_rowing_machine',
    name: 'Rowing Machine',
    primaryMuscle: MuscleGroup.cardio,
    secondaryMuscles: [MuscleGroup.back],
    equipment: Equipment.machine,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_jump_rope',
    name: 'Jump Rope',
    primaryMuscle: MuscleGroup.cardio,
    secondaryMuscles: [],
    equipment: Equipment.other,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_stair_climber',
    name: 'Stair Climber',
    primaryMuscle: MuscleGroup.cardio,
    secondaryMuscles: [MuscleGroup.glutes],
    equipment: Equipment.machine,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_elliptical',
    name: 'Elliptical',
    primaryMuscle: MuscleGroup.cardio,
    secondaryMuscles: [],
    equipment: Equipment.machine,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_battle_ropes',
    name: 'Battle Ropes',
    primaryMuscle: MuscleGroup.cardio,
    secondaryMuscles: [MuscleGroup.shoulders, MuscleGroup.core],
    equipment: Equipment.other,
    isCustom: false,
  ),

  // ── Full Body / Compound ──────────────────────────────────────────────────
  Exercise(
    id: 'ex_kettlebell_swing',
    name: 'Kettlebell Swing',
    primaryMuscle: MuscleGroup.fullBody,
    secondaryMuscles: [MuscleGroup.glutes, MuscleGroup.hamstrings, MuscleGroup.core],
    equipment: Equipment.kettlebell,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_clean_and_press',
    name: 'Clean and Press',
    primaryMuscle: MuscleGroup.fullBody,
    secondaryMuscles: [MuscleGroup.shoulders, MuscleGroup.back],
    equipment: Equipment.barbell,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_thruster',
    name: 'Thruster',
    primaryMuscle: MuscleGroup.fullBody,
    secondaryMuscles: [MuscleGroup.quads, MuscleGroup.shoulders],
    equipment: Equipment.barbell,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_burpee',
    name: 'Burpee',
    primaryMuscle: MuscleGroup.fullBody,
    secondaryMuscles: [],
    equipment: Equipment.bodyweight,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_turkish_get_up',
    name: 'Turkish Get-Up',
    primaryMuscle: MuscleGroup.fullBody,
    secondaryMuscles: [MuscleGroup.core, MuscleGroup.shoulders],
    equipment: Equipment.kettlebell,
    isCustom: false,
  ),
  Exercise(
    id: 'ex_power_clean',
    name: 'Power Clean',
    primaryMuscle: MuscleGroup.fullBody,
    secondaryMuscles: [MuscleGroup.back, MuscleGroup.hamstrings],
    equipment: Equipment.barbell,
    isCustom: false,
  ),
];
